apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzadelivery
  labels:
    app: pizzadelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzadelivery
  template:
    metadata:
      labels:
        app: pizzadelivery
    spec:
      containers:
        - name: pizzadelivery
          image: username/pizzadelivery:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5